#!/usr/bin/env node
// Auto-generated by native-js-bridge. Do not edit.

const { execFileSync } = require("node:child_process");
const path = require("node:path");

// npm resolves platform packages via the `os` and `cpu` fields in package.json,
// which are checked against process.platform and process.arch respectively.
// We use the same values here so the lookup key is always consistent.
const PACKAGES = {
	// __NATIVE_JS_BRIDGE_PACKAGES__
};

const key = `${process.platform}-${process.arch}`;
const entry = PACKAGES[key];
if (!entry) {
	console.error(
		`__BINARY__: unsupported platform ${process.platform}-${process.arch}`,
	);
	process.exit(1);
}

let bin;
try {
	const pkgDir = path.dirname(require.resolve(`${entry.name}/package.json`));
	bin = path.join(pkgDir, `__BINARY__${entry.binExt}`);
} catch (_e) {
	console.error(`__BINARY__: platform package ${entry.name} is not installed`);
	process.exit(1);
}

try {
	execFileSync(bin, process.argv.slice(2), { stdio: "inherit" });
} catch (e) {
	process.exit(e.status ?? 1);
}
